# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 23:03
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(blank=True, default='')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_modify_date', models.DateField()),
                ('privacy', models.CharField(blank=True, choices=[('all', 'public'), ('myself', 'yourself')], default='all', max_length=10)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('d', 'draft'), ('p', 'published')], default='d', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('posts', models.ManyToManyField(to='blog.Post')),
            ],
        ),
    ]
