# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'english'), ('cn', 'chinese')], default='en', max_length=5),
        ),
    ]
