# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-25 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160824_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='uri',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
